title: Chris Buckley
description: Dump a MySQL Workbench file using only XSLT and SQLite

url: https://cmbuckley.co.uk
baseurl: /mwbdump

repository: cmbuckley/mwbdump
remote_theme: "cmbuckley/cmbuckley.github.io"

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

social:
   keybase:   cmbuckley
   hackerone: cmbuckley
   github:    cmbuckley
   linkedin:  cmbuckley
   email:     chris@cmbuckley.co.uk
   twitter:   _cmbuckley
   facebook:  cmbuckley
   instagram: c.m.buckley
   amazon:    https://bux.re/amzn
